export const accountCatalog = [
  {
    id: "acc-01",
    code: "RD-1024",
    title: "Glacier X-Suit Vault",
    tag: "Hot drop",
    tier: "Mythic",
    tierClass: "tier-mythic",
    price: "6.900.000d",
    image: "/accounts/acc-01.svg",
    summary: "Kho do nang cap, glacier, lobby dep va bo badge de chot nguoi mua high tier.",
    stats: ["Level 76", "89 skin", "3 sung nang cap"],
    badges: [
      { label: "Glacier", className: "tag-dark" },
      { label: "89 skin", className: "tag-yellow" },
      { label: "Mythic", className: "tag-red" },
    ],
  },
  {
    id: "acc-02",
    code: "RD-1870",
    title: "Mythic Ranked Ready",
    tag: "Rank push",
    tier: "Elite",
    tierClass: "tier-elite",
    price: "4.500.000d",
    image: "/accounts/acc-02.svg",
    summary: "Tai khoan danh cho nguoi mua can vao tran ngay, rank dep va bo skin gon gang.",
    stats: ["Ace Master", "61 skin", "Kho do can bang"],
    badges: [
      { label: "Ace", className: "tag-dark" },
      { label: "61 skin", className: "tag-yellow" },
      { label: "Elite", className: "tag-green" },
    ],
  },
  {
    id: "acc-03",
    code: "RD-2201",
    title: "UC Bonus Full Set",
    tag: "Deal nhanh",
    tier: "Rare",
    tierClass: "tier-rare",
    price: "2.890.000d",
    image: "/accounts/acc-03.svg",
    summary: "Card hop cho nguoi mua tim deal dep, co UC bonus va nhieu set de doi gio.",
    stats: ["Level 68", "47 skin", "Set hiem 2022"],
    badges: [
      { label: "UC bonus", className: "tag-dark" },
      { label: "47 skin", className: "tag-yellow" },
      { label: "Rare", className: "tag-red" },
    ],
  },
  {
    id: "acc-04",
    code: "RD-3114",
    title: "Winner Pass Locker",
    tag: "Starter plus",
    tier: "Starter",
    tierClass: "tier-starter",
    price: "980.000d",
    image: "/accounts/acc-04.svg",
    summary: "Moc gia de vao, hinh card dep, phu hop lam diem chot o phan gia mem.",
    stats: ["Level 42", "28 skin", "Dang nhap on dinh"],
    badges: [
      { label: "Starter", className: "tag-dark" },
      { label: "28 skin", className: "tag-yellow" },
      { label: "Gia mem", className: "tag-green" },
    ],
  },
  {
    id: "acc-05",
    code: "RD-4128",
    title: "Stealth Crate Premium",
    tag: "Loadout dep",
    tier: "Elite",
    tierClass: "tier-elite",
    price: "3.750.000d",
    image: "/accounts/acc-05.svg",
    summary: "Phong cach trinh bay danh cho nhom acc can nhieu anh va visual noi bat o giua trang.",
    stats: ["Level 70", "54 skin", "2 emote hiem"],
    badges: [
      { label: "Premium", className: "tag-dark" },
      { label: "54 skin", className: "tag-yellow" },
      { label: "Elite", className: "tag-green" },
    ],
  },
  {
    id: "acc-06",
    code: "RD-5099",
    title: "Night Ops Collection",
    tag: "Kho hiem",
    tier: "Mythic",
    tierClass: "tier-mythic",
    price: "5.250.000d",
    image: "/accounts/acc-06.svg",
    summary: "Day la card dung de hoan thien gallery 6 anh, tao du nhip 2 hang 3 cot tren homepage.",
    stats: ["Level 73", "72 skin", "Outfit hiem"],
    badges: [
      { label: "Night ops", className: "tag-dark" },
      { label: "72 skin", className: "tag-yellow" },
      { label: "Mythic", className: "tag-red" },
    ],
  },
] as const;
